config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: "pages#home"

  resources :users, only: [:show], path: 'profile', as: :profile, param: :slug

  resources :events do
    resources :attendances, only: [:create]
    resources :comments, only: %i[create]
  end

  resources :posts do
    resources :comments, only: %i[create]
  end

  resources :comments, only: %i[destroy]
  resources :favorites, only: %i[index create destroy]
  resources :likes, only: %i[create destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favoritable, polymorphic: true

  validates :user, uniqueness: { scope: %i[favoritable_id favoritable_type] }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = policy_scope(Favorite).order(created_at: :desc)
  end

  def create
    @favoritable = favoritable
    @favorite = @favoritable.favorites.create
    @favorite.user = current_user
    authorize @favorite
    @favorite.save
    redirect_back_or_to root_path
  end

  def destroy
    @favorite = current_user.favorites.find_by(favoritable_id: params[:id])
    authorize @favorite
    @favorite.destroy
    redirect_back_or_to root_path
  end

  private

  def favoritable
    return Post.find(params[:post_id]) if params[:post_id]
    return Event.find(params[:event_id]) if params[:event_id]
  end
end

app/views/favorites/_favorite.html.erb
<% if favoritable.favorites.find_by(favoritable_id: favoritable.id, user: current_user) %>
  <%= link_to favorite_path(favoritable.id), data: {turbo_method: :delete} do %>
    <i class="fa-solid fa-bookmark"></i>
  <% end %>
<% else %>
  <%= link_to favorites_path("#{favoritable.class.to_s.downcase}_id": favoritable.id), data: {turbo_method: :post} do %>
    <i class="fa-regular fa-bookmark"></i>
  <% end %>
<% end %>

app/views/favorites/index.html.erb
<%= content_for(:title, 'Favorites | Greenly') %>

<div class="container">
  <main>
    <div class="row">
      <div class="col-md-3">
        <%= render 'shared/sidebar' %>
      </div>
      <div class="col-md-6">
        <%= render "shared/empty_state" if @favorites.empty? %>
        <% @favorites.each do |favorite| %>
          <% if favorite.favoritable_type == "Post" %>
            <%= render "posts/post", post: Post.find(favorite.favoritable_id) %>
          <% else %>
            <%= render "events/event", event: Event.find(favorite.favoritable_id) %>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-3">
        <%= render 'shared/right_side' %>
      </div>
      <div class="go-top-container" data-controller="utils" data-action="click->utils#goTop">
        <div class="go-top-button">
          <i class="fas fa-chevron-up"></i>
        </div>
      </div>
    </div>
  </main>
</div>