config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: "pages#home"

  resources :users, only: [:show], path: 'profile', as: :profile, param: :slug

  resources :events do
    resources :attendances, only: [:create]
    resources :comments, only: %i[create]
  end

  resources :posts do
    resources :comments, only: %i[create]
  end

  resources :comments, only: %i[destroy]
  resources :favorites, only: %i[index create destroy]
  resources :likes, only: %i[create destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  validates :user, uniqueness: { scope: %i[likeable_id likeable_type] }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @likeable = likeable
    @like = @likeable.likes.create
    @like.user = current_user
    authorize @like
    @like.save
    redirect_back_or_to root_path
  end

  def destroy
    @like = current_user.likes.find_by(likeable_id: params[:id])
    authorize @like
    @like.destroy
    redirect_back_or_to root_path
  end

  private

  def likeable
    return Post.find(params[:post_id]) if params[:post_id]
    return Event.find(params[:event_id]) if params[:event_id]
  end
end

app/views/likes/_like.html.erb
<% if likeable.likes.find_by(likeable_id: likeable.id, user: current_user) %>
  <%= link_to like_path(likeable.id), data: {turbo_method: :delete} do %>
    <i class="fa-solid fa-heart" style="color:#ED553B;"></i>
  <% end %>
<% else %>
  <%= link_to likes_path("#{likeable.class.to_s.downcase}_id": likeable.id), data: {turbo_method: :post} do %>
    <i class="fa-regular fa-heart"></i>
  <% end %>
<% end %>

app/views/likes/_likes.html.erb
<% if likeable.likes.any? %>
  <% likeable.likes.last(5).each do |like| %>
    <span><%= cl_image_tag like.user.photo.key, width: 23, height: 23, crop: :fill %></span>
  <% end %>
  <p>
    Liked by <b><%= likeable.likes.last.user.first_name %></b>
    <% if likeable.likes.count > 1 %>
      and <b><%= pluralize(likeable.likes.count - 1, "user") %></b> more
    <% end %>
  </p>
<% end %>