config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: "pages#home"

  resources :users, only: [:show], path: 'profile', as: :profile, param: :slug

  resources :events do
    resources :attendances, only: [:create]
    resources :comments, only: %i[create]
  end

  resources :posts do
    resources :comments, only: %i[create]
  end

  resources :comments, only: %i[destroy]
  resources :favorites, only: %i[index create destroy]
  resources :likes, only: %i[create destroy]
end

app/views/shared/_dropdown.html.erb
<div class="dropdown">
  <span role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <i class="fa-sharp fa-solid fa-ellipsis"></i>
  </span>

  <ul class="dropdown-menu border-radius">
    <% if item.user == current_user %>
      <li class="dropdown-item">
        <% if policy(item).update? %>
          <%= link_to "edit", send("edit_#{item.class.to_s.downcase}_path", item),
          data: { turbo_frame: "remote_modal" }, class: "dropdown-item"%>
        <% end %>
      </li>
      <li class="dropdown-item">
        <% if policy(item).destroy? %>
          <div data-controller="sweetalert">
            <span class="invisible">
              <%= link_to "", send("#{item.class.to_s.downcase}_path", item),
              data: { sweetalert_target: "deleteButton", turbo_method: :delete } %>
            </span>
            <div data-action="click->sweetalert#confirmAlert" class="dropdown-item" style="cursor:pointer;">
              Delete
            </div>
          </div>
        <% end %>
      </li>
    <% else %>
      <li class="dropdown-item" style="cursor:pointer;">
        <div data-controller="sweetalert" data-action="click->sweetalert#fakeReport">
          Report
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_empty_state.html.erb
<div class="w-100 text-center empty-state">
  You don't have any content yet!
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-primary mt-auto">
  <div class="container text-white">
    <div class="row mt-3">
      <div class="col-md-4">
        <p>Greenly, todos los derechos resevados. ©2022</p>
      </div>
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <ul class="list-inline text-end">
            <li class="list-inline-item">
              <li class="fa-brands fa-facebook-f"></li>
            </li>
            <li class="list-inline-item">
              <li class="fa-brands fa-twitter text-light"></li>
            </li>
            <li class="list-inline-item">
              <li class="fa-brands fa-instagram text-light"></li>
            </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal" tabindex="-1" data-controller="remote-modal">
    <div class="modal-dialog">
      <div class="modal-content border-radius">
        <div class="modal-header">
          <h5 class="modal-title"><%= title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <div class="container">
    <%= link_to root_path, class: "log" do %>
      <%= image_tag "greenly.ico", style: "width: 40px; height: 40px", alt: "Greenly icon" %>
    <% end %>
    <% if user_signed_in? %>
      <div class="search-bar" data-controller="sweetalert" data-action="input->sweetalert#fakeReport">
          <i class="fa-solid fa-magnifying-glass"></i>
          <input type="search" placeholder="Search for people, post and events">
      </div>

      <div class="create">
        <div class="btn-group">
          <%= link_to "Community", posts_path, class: "btn btn-primary btn-lg" %>
          <button type="button" class="btn btn-lg btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu border-radius">
            <li><%= link_to "Create Post", new_post_path, data: { turbo_frame: "remote_modal" }, class: "dropdown-item" %></li>
            <li><%= link_to "Create Event", new_event_path, data: { turbo_frame: "remote_modal" }, class: "dropdown-item" %></li>
            <li><%= link_to "Events", events_path, class: "dropdown-item" %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
          </ul>
        </div>

        <div class="profile-photo">
          <%= link_to profile_path(current_user) do %>
            <%= cl_image_tag current_user.photo.key, alt: "User profile" %>
          <% end %>
        </div>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</nav>

app/views/shared/_right_side.html.erb
<div class="right__side">
  <div class="mini__card">
    <h3 class="text-center">This week on Greenly</h3>
    <a href="#" target="_blank">
      <%= image_tag "sembrar_tomates.jpg", class: "photo" %>
    </a>
    <div class="text">
      <p>How to grow tomatoes in home</p>
    </div>
  </div>
  <% if user_signed_in? %>
    <%= link_to "Create a new Event", new_event_path, data: { turbo_frame: "remote_modal" }, class: "btn btn-primary" %>
  <% end %>
  <div class="footer mt-3" data-controller="sweetalert" data-action="click->sweetalert#fakeReport">
    <div class="text-center">
      <span class="mx-3">About</span>
      <span class="mx-3">Accessibility</span>
      <span class="mx-3">Language</span>
    </div>
    <div class="text-center m-3">
      <span class="mx-3">Privacy</span>
      <span class="mx-3">Conditions</span>
    </div>
    <div class="text-center">
      <span class="mx-3">Greenly © 2022. All rights reserved </span>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>
  <div class="info-left">
    <div class="profile">
      <div class="profile-photo">
          <%= cl_image_tag current_user.photo.key %>
      </div>
      <%= link_to profile_path(current_user), class: "profile-info" do %>
        <p><%= current_user.full_name %></p>
        <p class="text-muted">@<%= current_user.username %></p>
      <% end %>
    </div>
    <div class="sidebar">
      <%= link_to root_path, class: "menu-item" do %>
          <span><i class="fa-solid fa-house fa-fw"></i></span>
          <h3>Home</h3>
      <% end %>
      <%= link_to posts_path, class: "menu-item" do %>
          <span><i class="fa-solid fa-user-group fa-fw"></i></span>
          <h3>Community</h3>
      <% end %>
      <%= link_to events_path, class: "menu-item" do %>
          <span><i class="fa-solid fa-calendar-days fa-fw"></i></span>
          <h3>Events</h3>
      <% end %>
      <%= link_to favorites_path, class: "menu-item" do %>
          <span><i class="fa-solid fa-heart fa-fw"></i></span>
          <h3>Favorites</h3>
      <% end %>
        <a class="menu-item" data-controller="sweetalert" data-action="click->sweetalert#fakeReport">
            <span><i class="fa-solid fa-palette fa-fw"></i></span>
            <h3>Theme</h3>
        </a>
        <a class="menu-item" data-controller="sweetalert" data-action="click->sweetalert#fakeReport">
            <span><i class="fa-solid fa-gear fa-fw"></i></span>
            <h3>Settings</h3>
        </a>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "menu-item" do %>
          <span><i class="fa-solid fa-arrow-left fa-fw"></i></span>
          <h3>Log Out</h3>
      <% end %>
    </div>
    <%= link_to "Create Post", new_post_path, data: { turbo_frame: "remote_modal" }, class: "btn btn-primary mb-3" %>
  </div>
<% else %>
  <div class="info-left">
  <div class="profile">
    <div class="profile-info">
      <p class="text-center">Greenly is a social network for people who care about the environment.</p>
    </div>
  </div>
    <div class="sidebar">
      <%= link_to root_path, class: "menu-item" do %>
          <span><i class="fa-solid fa-house fa-fw"></i></span>
          <h3>Home</h3>
      <% end %>
      <a class="menu-item" data-controller="sweetalert" data-action="click->sweetalert#fakeReport">
            <span><i class="fa-solid fa-palette fa-fw"></i></span>
            <h3>Theme</h3>
        </a>
      <%= link_to events_path, class: "menu-item" do %>
          <span><i class="fa-solid fa-calendar-days fa-fw"></i></span>
          <h3>Events</h3>
      <% end %>
    </div>
  </div>
<% end %>