config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: "pages#home"

  resources :users, only: [:show], path: 'profile', as: :profile, param: :slug

  resources :events do
    resources :attendances, only: [:create]
    resources :comments, only: %i[create]
  end

  resources :posts do
    resources :comments, only: %i[create]
  end

  resources :comments, only: %i[destroy]
  resources :favorites, only: %i[index create destroy]
  resources :likes, only: %i[create destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  include ImageType
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :favorites, as: :favoritable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :photo

  validates :content, presence: true, length: { minimum: 3, maximum: 1000 }
  validates :photo, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = policy_scope(Post).includes(:user, :comments).with_attached_photo.order(created_at: :desc)
    @pagy, @posts = pagy_countless(@posts, items: 10)
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post
    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @post
  end

  def show
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    authorize @post
    redirect_back_or_to posts_path, status: :see_other
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :photo)
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :content, label: "Post Content", placeholder: "What's on your mind?", input_html: { rows: 5 } %>
  <%= f.input :photo, as: :file, label: "Post Photo", hint: "Share a photo with the community" %>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="white__card" data-controller="share" data-share-url-value="<%= post_url(post) %>">
  <div class="head">
    <div class="user">
      <div class="card-profile-photo">
        <%= cl_image_tag post.user.photo.key, alt: "Profile Photo"%>
      </div>
      <div>
        <p class="fw-bold" data-share-target="title"><%= post.user.full_name %></p>
        <small class="mt-0">Colombia, <%= distance_of_time_in_words_to_now(post.created_at) %> ago</small>
      </div>
    </div>
    <span class="edit">
      <%= render partial: "shared/dropdown", locals: { item: post } %>
    </span>
  </div>
  <div class="photo">
    <%= link_to post_path(post) do %>
      <%= cl_image_tag post.photo.key, alt: "Post Image" if post.photo.attached? %>
    <% end %>
  </div>
  <div class="action-buttons">
    <div class="interaction-buttons">
        <span><%= render "likes/like", likeable: post %></span>
        <span><i class="fa-regular fa-comment-dots"></i></span>
        <span data-action="click->share#share"><i class="fa-solid fa-retweet"></i></i></span>
    </div>
    <div class="bookmark">
        <span><%= render "favorites/favorite", favoritable: post %></span>
    </div>
  </div>
  <div class="liked-by">
    <%= render "likes/likes", likeable: post %>
  </div>
  <div class="card__details">
    <p data-share-target="description"><%= post.content %></p>
    <%= content_tag(:div, "", class: "mb-2", data:{share_target: "result"}) %>
  </div>
  <%= render partial: "comments/comment_form", locals: { commentable: post } %>
  <div class="card__comments">
    <%= render partial: "comments/comments", locals: { commentable: post } %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= content_for(:title, 'Edit post | Greenly') %>

<%= render "shared/modal", title: "Edit Post" do %>
  <%= render "form", post: @post %>
<% end %>

app/views/posts/index.html.erb
<%= content_for(:title, 'Comunidad | Greenly') %>

<div class="container">
  <main>
    <div class="row">
      <div class="col-md-3">
        <%= render 'shared/sidebar' %>
      </div>
      <div class="col-md-6">

        <%= render "shared/empty_state" if @posts.empty? %>

        <%= turbo_frame_tag "posts-#{@pagy.page}", class: "posts" do %>
          <%= render @posts %>
          <% if @pagy.next %>
            <%= turbo_frame_tag "posts-#{@pagy.next}", loading: :lazy, class: "posts",
            src: pagy_url_for(@pagy, @pagy.next) %>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-3">
        <%= render 'shared/right_side' %>
      </div>
      <div class="go-top-container" data-controller="utils" data-action="click->utils#goTop">
        <div class="go-top-button">
          <i class="fas fa-chevron-up"></i>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/posts/new.html.erb
<%= content_for(:title, 'New Post | Greenly') %>

<%= render "shared/modal", title: "New Post" do %>
  <%= render "form", post: @post %>
<% end %>

app/views/posts/show.html.erb
<%= content_for(:title, 'Post details | Greenly') %>
<% content_for(:meta_description, @post.content) %>
<% content_for(:meta_image, cl_image_tag(@post.photo.key), width: 1200, height: 630, crop: :fill) %>

<div class="container">
  <main>
    <div class="row">
      <div class="col-md-8">
        <div class="white__card" data-controller="share" data-share-url-value="<%= post_url(@post) %>">
          <div class="head">
            <div class="user">
              <div class="card-profile-photo">
                <%= cl_image_tag @post.user.photo.key, alt: "Profile Photo"%>
              </div>
              <div>
                <p class="fw-bold" data-share-target="title"><%= @post.user.full_name %></p>
                <small class="mt-0">Colombia, <%= distance_of_time_in_words_to_now(@post.created_at) %> ago</small>
              </div>
            </div>
            <span class="edit">
              <%= render partial: "shared/dropdown", locals: { item: @post } %>
            </span>
          </div>
          <div class="photo">
            <%= cl_image_tag @post.photo.key, alt: "Post Image" if @post.photo.attached? %>
          </div>
          <div class="action-buttons">
            <div class="interaction-buttons">
              <span><%= render "likes/like", likeable: @post %></span>
              <span><i class="fa-regular fa-comment-dots"></i></span>
              <span data-action="click->share#share"><i class="fa-sharp fa-solid fa-share-nodes"></i></span>
            </div>
            <div class="bookmark">
              <span><%= render "favorites/favorite", favoritable: @post %></span>
            </div>
          </div>
          <div class="liked-by">
            <%= render "likes/likes", likeable: @post %>
          </div>
          <div class="card__details">
            <p data-share-target="description"><%= @post.content %></p>
            <%= content_tag(:div, "", class: "mb-2", data:{share_target: "result"}) %>
          </div>
          <%= render partial: "comments/comment_form", locals: { commentable: @post } %>
          <div class="card__comments">
            <%= render partial: "comments/comments", locals: { commentable: @post } %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <%= render 'shared/right_side' %>
      </div>
      <div class="go-top-container" data-controller="utils" data-action="click->utils#goTop">
        <div class="go-top-button">
          <i class="fas fa-chevron-up"></i>
        </div>
      </div>
    </div>
  </main>
</div>